(()=>{'use strict';
const C=IeumCore,$=id=>document.getElementById(id),KEY='ieum.daytrace.v1';let data={version:1,entries:[]},editing=null,mood='',pending=null,blocked=false,timeChanged=false;
const say=(message,error=false)=>{$('status').textContent=message;$('status').classList.toggle('error',error);};
try{const raw=localStorage.getItem(KEY);if(raw!==null)data=C.validate(JSON.parse(raw));}catch(e){blocked=true;say('기존 기록을 읽지 못했어요. 덮어쓰지 않도록 저장을 멈췄어요. 브라우저 데이터를 지우지 말고 이음에게 알려주세요.',true);}
function commit(next){if(blocked){say('저장이 중지된 상태예요. 기존 기록을 먼저 확인해야 해요.',true);return false;}try{const clean=C.validate(next);localStorage.setItem(KEY,JSON.stringify(clean));data=clean;return true;}catch(e){say('저장하지 못했어요. 입력 내용은 그대로 남겨 두었어요. 저장 공간이나 브라우저 설정을 확인해 주세요.',true);return false;}}
// Re-read immediately before writing to avoid overwriting changes from another tab.
function latest(){try{const raw=localStorage.getItem(KEY);return raw===null?{version:1,entries:[]}:C.validate(JSON.parse(raw));}catch(e){blocked=true;throw e;}}
function change(fn){try{return commit(fn(latest()));}catch(e){say('기록을 안전하게 읽지 못해 변경하지 않았어요.',true);return false;}}
function show(which){for(const name of ['write','history','manage']){$(name+'Panel').hidden=name!==which;$(name+'Tab').removeAttribute('aria-current');}$(which+'Tab').setAttribute('aria-current','page');render();}
for(const name of ['write','history','manage'])$(name+'Tab').onclick=()=>show(name);
C.moods.forEach(value=>{const b=document.createElement('button');b.type='button';b.textContent=value;b.setAttribute('aria-pressed','false');b.onclick=()=>{mood=mood===value?'':value;paintMood();};$('moods').append(b);});
function paintMood(){for(const b of $('moods').children)b.setAttribute('aria-pressed',String(b.textContent===mood));}
function reset(){editing=null;mood='';timeChanged=false;$('entryForm').reset();$('eventTime').value=C.localValue();$('cancelEdit').hidden=true;$('formTitle').textContent='지금 한 줄';$('saveButton').textContent='이 순간 저장';paintMood();}
$('eventTime').oninput=()=>{timeChanged=true;};
$('entryForm').onsubmit=event=>{event.preventDefault();const note=$('note').value.trim();if(!note&&!mood){say('기분을 고르거나 한 줄을 적어 주세요.',true);return;}const now=new Date();const when=timeChanged||editing?new Date($('eventTime').value):now;if(!Number.isFinite(when.getTime())||when>now){say('기록 시각은 지금 또는 과거로 선택해 주세요.',true);return;}const id=editing||crypto.randomUUID();let missing=false;const ok=change(current=>{const old=current.entries.find(e=>e.id===id);if(editing&&(!old||old.deletedAt)){missing=true;throw Error('missing');}const entry={id,note,mood,situation:$('situation').value,eventAt:when.toISOString(),createdAt:old?old.createdAt:now.toISOString(),updatedAt:now.toISOString(),deletedAt:null};return {version:1,entries:[...current.entries.filter(e=>e.id!==id),entry]};});if(ok){reset();say('이 브라우저에 저장했어요.');show('history');}else if(missing)say('다른 화면에서 삭제된 기록이에요. 입력 내용을 복사해 새 기록으로 남겨 주세요.',true);};
$('cancelEdit').onclick=()=>{reset();say('수정을 취소했어요.');show('history');};
const fmt=value=>new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function action(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
function card(e,trash=false){const article=el('article',undefined,'entry');article.append(el('h3',fmt(e.eventAt)),el('div',[e.situation,e.mood].filter(Boolean).join(' · '),'chips'));if(e.note)article.append(el('p',e.note));article.append(el('div','직접 남긴 기록 · 저장 '+fmt(e.createdAt)+(e.updatedAt!==e.createdAt?' · 수정 '+fmt(e.updatedAt):''),'meta'));const row=el('div',undefined,'row');if(trash){row.append(action('이 기록 복구',()=>{if(change(d=>({...d,entries:d.entries.map(x=>x.id===e.id?{...x,deletedAt:null}:x)}))){say('기록을 복구했어요.');render();}}));}else{row.append(action('수정',()=>{editing=e.id;mood=e.mood;timeChanged=true;$('note').value=e.note;$('situation').value=e.situation;$('eventTime').value=C.localValue(e.eventAt);$('cancelEdit').hidden=false;$('formTitle').textContent='기록 수정';$('saveButton').textContent='수정 저장';paintMood();show('write');$('formTitle').scrollIntoView({block:'start'});}),action('삭제',()=>{if(change(d=>({...d,entries:d.entries.map(x=>x.id===e.id?{...x,deletedAt:new Date().toISOString()}:x)}))){say('휴지통으로 옮겼어요. 보관·관리에서 복구할 수 있어요.');render();}}));}article.append(row);return article;}
function render(){const items=data.entries.filter(e=>!e.deletedAt).sort((a,b)=>Date.parse(b.eventAt)-Date.parse(a.eventAt)),day=$('dayFilter').value,filtered=items.filter(e=>!day||C.localValue(e.eventAt).slice(0,10)===day);$('entries').replaceChildren(...filtered.map(e=>card(e)));if(!filtered.length)$('entries').append(el('p',items.length?'이 날짜에는 기록이 없어요.':'아직 기록이 없어요. 지금의 기분 하나부터 남겨 보세요.','empty'));$('entryCount').textContent=filtered.length+'개의 흔적';const trash=data.entries.filter(e=>e.deletedAt).sort((a,b)=>Date.parse(b.deletedAt)-Date.parse(a.deletedAt));$('trash').replaceChildren(...trash.map(e=>card(e,true)));if(!trash.length)$('trash').append(el('p','삭제한 기록이 없어요.','hint'));}
$('dayFilter').onchange=render;$('allDays').onclick=()=>{$('dayFilter').value='';render();};
$('exportButton').onclick=()=>{try{const backup=latest(),blob=new Blob([JSON.stringify({...backup,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='이음-하루기록-'+C.localValue().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);say('백업 내려받기를 요청했어요. 다운로드 폴더에 파일이 생겼는지 확인해 주세요.');}catch(e){say('백업을 만들지 못했어요. 기존 기록을 지우지 말고 이음에게 알려주세요.',true);}};
$('importFile').onchange=async()=>{pending=null;$('importReview').hidden=true;const f=$('importFile').files[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error('파일이 너무 커요.');pending=C.validate(JSON.parse(await f.text()));const current=latest(),result=C.merge(current,pending);$('importSummary').textContent=`파일 ${pending.entries.length}건 중 새 기록 ${result.entries.length-current.entries.length}건을 추가합니다. 같은 ID의 기록은 현재 내용을 유지합니다. 휴지통 기록도 포함합니다.`;$('importReview').hidden=false;}catch(e){say('복원할 수 없는 파일이에요. 현재 기록은 변경하지 않았어요.',true);}};
function clearImport(){pending=null;$('importFile').value='';$('importReview').hidden=true;}
$('cancelImport').onclick=clearImport;$('restoreButton').onclick=()=>{if(pending&&change(d=>C.merge(d,pending))){clearImport();render();say('백업의 새 기록을 복원했어요.');}};
window.addEventListener('storage',e=>{if(e.key===KEY){try{data=latest();render();say(editing?'다른 화면에서 기록이 바뀌었어요. 수정 저장 전 내용을 확인해 주세요.':'다른 화면의 변경을 반영했어요.');}catch(err){say('기록을 읽지 못했어요. 변경을 멈춰 주세요.',true);}}});
reset();render();if(blocked)$('saveButton').disabled=true;
})();
